name: Test action
on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:
    inputs:
      quality:
        required: false
        options:
          - stable
          - insider
        type: choice

jobs:
  test:
    name: Test on ${{ matrix.runner }}
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        runner: [ubuntu-24.04, ubuntu-24.04-arm, macos-13, macos-14, windows-latest]
    steps:
    - uses: actions/checkout@v4.2.2
    - uses: ./
      with:
        quality: ${{ inputs.quality || 'stable' }}
